version: '3'
services:
  bigstream:
    image: "bigstream:${TAG}"
    build: ./bigstream/
    container_name: node_bigstream
    networks:
     - frontend
     - backend
    ports:
     - "19980:19980"
     - "19080:19080"
     - "19180:19180"
    volumes:
     - ./bigstreamdata:/var/bigstream/data
  redis:
    image: "redis:3.2.11"
    command: redis-server --appendonly yes
    container_name: redis_bigstream
    networks:
     - backend
    volumes:
     - ./redis/data:/data
  rabbitmq:
    image: "rabbitmq:3.6.12"
    command: rabbitmq-server --hostname rabbitmq_bigstream
    container_name: rabbitmq_bigstream
    networks:
     - backend
    volumes:
     - ./rabbitmq/rabbitconf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
     - ./rabbitmq/home:/var/lib/rabbitmq
networks:
  frontend:
  backend:
